layout_spectrum: 0.6630824
color:
  saturation: 0.06810036
  lightness: 0.5860215
  brandStrength: 0.1487455
  brandColors:
    - '#301E1F'
    - '#F1EACF'
    - '#5C665A'
    - '#9A654B'
    - '#CF9A6E'
  rhythmicContrast: 0.8082438
typography_spectrum: 0.1397849
name: Mike Shaffer
